// <auto-generated />
using System;
using ANLairQuotationSystem.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ANLairQuotationSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260905073806_AddedContentTypeAndCaptionInItemImage")]
    partial class AddedContentTypeAndCaptionInItemImage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ANLairQuotationSystem.Entities.Client", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("address");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("company_name");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("contact_number");

                    b.Property<uint>("CreatorId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("creator_id");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime>("DateModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_modified")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("ExtensionName")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("extension_name");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("firstname");

                    b.Property<string>("Middlename")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("middlename");

                    b.Property<string>("Position")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("position");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("char(15)")
                        .HasColumnName("public_id");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("surname");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("ix_clients_creator_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_clients_public_id");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.ComputationConstant", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime>("DateModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_modified")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<int>("Operator")
                        .HasColumnType("int")
                        .HasColumnName("operator");

                    b.Property<decimal>("Value")
                        .HasPrecision(13, 2)
                        .HasColumnType("decimal(13,2)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_computation_constants");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_computation_constants_name");

                    b.ToTable("computation_constants", (string)null);
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.Item", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("contact_number");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime>("DateModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_modified")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("DistributorName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("distributor_name");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<decimal>("FinalCost")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("final_cost");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<uint>("TypeId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("type_id");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("unique_id");

                    b.HasKey("Id")
                        .HasName("pk_items");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_items_type_id");

                    b.HasIndex("UniqueId")
                        .IsUnique()
                        .HasDatabaseName("ix_items_unique_id");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.ItemExpense", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<decimal>("Cost")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("cost");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime>("DateModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_modified")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("description");

                    b.Property<uint>("ItemId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("item_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_item_expenses");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_item_expenses_item_id");

                    b.ToTable("item_expenses", (string)null);
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.ItemImage", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<string>("Caption")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("caption");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime>("DateModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_modified")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("MEDIUMBLOB")
                        .HasColumnName("image");

                    b.Property<uint>("ItemId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("item_id");

                    b.HasKey("Id")
                        .HasName("pk_item_images");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_item_images_item_id");

                    b.ToTable("item_images", (string)null);
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.ItemSpecification", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime>("DateModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_modified")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("description");

                    b.Property<uint>("ItemId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("item_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_item_specifications");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_item_specifications_item_id");

                    b.ToTable("item_specifications", (string)null);
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.ItemType", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime>("DateModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_modified")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_item_types");

                    b.ToTable("item_types", (string)null);
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.Permission", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime>("DateModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_modified")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_permissions_name");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.Project", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<uint>("ClientId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("client_id");

                    b.Property<uint>("CreatorId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("creator_id");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime>("DateModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_modified")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime>("DateRequested")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_requested");

                    b.Property<string>("HospitalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("hospital_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("RequestorExtensionName")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("requestor_extension_name");

                    b.Property<string>("RequestorFirstname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("requestor_firstname");

                    b.Property<string>("RequestorMiddlename")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("requestor_middlename");

                    b.Property<string>("RequestorPosition")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("requestor_position");

                    b.Property<string>("RequestorSurname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("requestor_surname");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("unique_id");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_projects_client_id");

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("ix_projects_creator_id");

                    b.HasIndex("UniqueId")
                        .IsUnique()
                        .HasDatabaseName("ix_projects_unique_id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.ProjectItem", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("contact_number");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime>("DateModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_modified")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("DistributorName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("distributor_name");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<decimal>("FinalCost")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("final_cost");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<uint>("ProjectId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("project_id");

                    b.Property<uint>("TypeId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("type_id");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("unique_id");

                    b.HasKey("Id")
                        .HasName("pk_project_items");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_items_project_id");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_project_items_type_id");

                    b.ToTable("project_items", (string)null);
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.ProjectItemExpense", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<decimal>("Cost")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("cost");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime>("DateModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_modified")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<uint>("ProjectItemId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("project_item_id");

                    b.HasKey("Id")
                        .HasName("pk_project_item_expenses");

                    b.HasIndex("ProjectItemId")
                        .HasDatabaseName("ix_project_item_expenses_project_item_id");

                    b.ToTable("project_item_expenses", (string)null);
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.ProjectItemImage", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<string>("Caption")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("caption");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime>("DateModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_modified")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("MEDIUMBLOB")
                        .HasColumnName("image");

                    b.Property<uint>("ProjectItemId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("project_item_id");

                    b.HasKey("Id")
                        .HasName("pk_project_item_images");

                    b.HasIndex("ProjectItemId")
                        .HasDatabaseName("ix_project_item_images_project_item_id");

                    b.ToTable("project_item_images", (string)null);
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.ProjectItemSpecification", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime>("DateModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_modified")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<uint>("ProjectItemId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("project_item_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_project_item_specifications");

                    b.HasIndex("ProjectItemId")
                        .HasDatabaseName("ix_project_item_specifications_project_item_id");

                    b.ToTable("project_item_specifications", (string)null);
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.ProjectRequestProof", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<uint>("CreatorId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("creator_id");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<byte[]>("PhotoConfirmation")
                        .IsRequired()
                        .HasColumnType("MEDIUMBLOB")
                        .HasColumnName("photo_confirmation");

                    b.Property<uint>("ProjectId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("pk_project_request_proofs");

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("ix_project_request_proofs_creator_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_request_proofs_project_id");

                    b.ToTable("project_request_proofs", (string)null);
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.Quotation", b =>
                {
                    b.Property<uint>("ProjectId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("project_id");

                    b.Property<decimal>("FinalCost")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("final_cost");

                    b.Property<decimal>("ItemsFinalCost")
                        .HasPrecision(13, 2)
                        .HasColumnType("decimal(13,2)")
                        .HasColumnName("items_final_cost");

                    b.HasKey("ProjectId")
                        .HasName("pk_quotations");

                    b.ToTable("quotations", (string)null);
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.QuotationAdditional", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<decimal>("Cost")
                        .HasPrecision(13, 2)
                        .HasColumnType("decimal(13,2)")
                        .HasColumnName("cost");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime>("DateModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_modified")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<int>("Operator")
                        .HasColumnType("int")
                        .HasColumnName("operator");

                    b.Property<uint>("QuotationId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("quotation_id");

                    b.HasKey("Id")
                        .HasName("pk_quotation_additionals");

                    b.HasIndex("QuotationId")
                        .HasDatabaseName("ix_quotation_additionals_quotation_id");

                    b.ToTable("quotation_additionals", (string)null);
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.QuotationComputationConstant", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime>("DateModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_modified")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<int>("Operator")
                        .HasColumnType("int")
                        .HasColumnName("operator");

                    b.Property<uint>("QuotationId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("quotation_id");

                    b.Property<decimal>("Value")
                        .HasPrecision(13, 2)
                        .HasColumnType("decimal(13,2)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_quotation_computation_constants");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_quotation_computation_constants_name");

                    b.HasIndex("QuotationId")
                        .HasDatabaseName("ix_quotation_computation_constants_quotation_id");

                    b.ToTable("quotation_computation_constants", (string)null);
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.Role", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime>("DateModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_modified")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1u,
                            DateCreated = new DateTime(2026, 8, 16, 10, 25, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Employee"
                        },
                        new
                        {
                            Id = 2u,
                            DateCreated = new DateTime(2026, 8, 16, 10, 25, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Sales Support"
                        },
                        new
                        {
                            Id = 3u,
                            DateCreated = new DateTime(2026, 8, 16, 10, 25, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Project Officer"
                        },
                        new
                        {
                            Id = 4u,
                            DateCreated = new DateTime(2026, 8, 16, 10, 25, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Senior Manager"
                        },
                        new
                        {
                            Id = 5u,
                            DateCreated = new DateTime(2026, 8, 16, 10, 25, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.RolePermission", b =>
                {
                    b.Property<uint>("RoleId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("role_id");

                    b.Property<uint>("PermissionId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.User", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("contact_number");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime>("DateModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_modified")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("ExtensionName")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("extension_name");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("firstname");

                    b.Property<string>("Middlename")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("middlename");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("password");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("public_id");

                    b.Property<uint>("RoleId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("role_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("surname");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_public_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_users_role_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.UserSession", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime>("DateExpiring")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_expiring")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("refresh_token");

                    b.Property<uint>("UserId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_sessions");

                    b.HasIndex("RefreshToken")
                        .IsUnique()
                        .HasDatabaseName("ix_user_sessions_refresh_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_sessions_user_id");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.Client", b =>
                {
                    b.HasOne("ANLairQuotationSystem.Entities.User", "CreatorUser")
                        .WithMany("CreatedClients")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clients_users_creator_id");

                    b.Navigation("CreatorUser");
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.Item", b =>
                {
                    b.HasOne("ANLairQuotationSystem.Entities.ItemType", "Type")
                        .WithMany("Items")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_items_item_types_type_id");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.ItemExpense", b =>
                {
                    b.HasOne("ANLairQuotationSystem.Entities.Item", "Item")
                        .WithMany("ItemExpenses")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_expenses_items_item_id");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.ItemImage", b =>
                {
                    b.HasOne("ANLairQuotationSystem.Entities.Item", "Item")
                        .WithMany("ItemImages")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_images_items_item_id");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.ItemSpecification", b =>
                {
                    b.HasOne("ANLairQuotationSystem.Entities.Item", "Item")
                        .WithMany("ItemSpecifications")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_specifications_items_item_id");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.Project", b =>
                {
                    b.HasOne("ANLairQuotationSystem.Entities.Client", "Client")
                        .WithMany("ClientProjects")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_projects_clients_client_id");

                    b.HasOne("ANLairQuotationSystem.Entities.User", "Creator")
                        .WithMany("CreatedProjects")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_projects_users_creator_id");

                    b.Navigation("Client");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.ProjectItem", b =>
                {
                    b.HasOne("ANLairQuotationSystem.Entities.Project", "Project")
                        .WithMany("ProjectItems")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_items_projects_project_id");

                    b.HasOne("ANLairQuotationSystem.Entities.ItemType", "Type")
                        .WithMany("ProjectItems")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_items_item_types_type_id");

                    b.Navigation("Project");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.ProjectItemExpense", b =>
                {
                    b.HasOne("ANLairQuotationSystem.Entities.ProjectItem", "ProjectItem")
                        .WithMany("ProjectItemExpenses")
                        .HasForeignKey("ProjectItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_item_expenses_project_items_project_item_id");

                    b.Navigation("ProjectItem");
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.ProjectItemImage", b =>
                {
                    b.HasOne("ANLairQuotationSystem.Entities.ProjectItem", "ProjectItem")
                        .WithMany("ProjectItemImages")
                        .HasForeignKey("ProjectItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_item_images_project_items_project_item_id");

                    b.Navigation("ProjectItem");
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.ProjectItemSpecification", b =>
                {
                    b.HasOne("ANLairQuotationSystem.Entities.ProjectItem", "ProjectItem")
                        .WithMany("ProjectItemSpecifications")
                        .HasForeignKey("ProjectItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_item_specifications_project_items_project_item_id");

                    b.Navigation("ProjectItem");
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.ProjectRequestProof", b =>
                {
                    b.HasOne("ANLairQuotationSystem.Entities.User", "Creator")
                        .WithMany("CreatedProjectRequestProofs")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_request_proofs_users_creator_id");

                    b.HasOne("ANLairQuotationSystem.Entities.Project", "Project")
                        .WithMany("ProjectRequestProofs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_request_proofs_projects_project_id");

                    b.Navigation("Creator");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.Quotation", b =>
                {
                    b.HasOne("ANLairQuotationSystem.Entities.Project", "Project")
                        .WithOne("Quotation")
                        .HasForeignKey("ANLairQuotationSystem.Entities.Quotation", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quotations_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.QuotationAdditional", b =>
                {
                    b.HasOne("ANLairQuotationSystem.Entities.Quotation", "Quotation")
                        .WithMany("QuotationAdditionals")
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quotation_additionals_quotations_quotation_id");

                    b.Navigation("Quotation");
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.QuotationComputationConstant", b =>
                {
                    b.HasOne("ANLairQuotationSystem.Entities.Quotation", "Quotation")
                        .WithMany("QuotationComputationConstants")
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quotation_computation_constants_quotations_quotation_id");

                    b.Navigation("Quotation");
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.RolePermission", b =>
                {
                    b.HasOne("ANLairQuotationSystem.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("ANLairQuotationSystem.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.User", b =>
                {
                    b.HasOne("ANLairQuotationSystem.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_roles_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.UserSession", b =>
                {
                    b.HasOne("ANLairQuotationSystem.Entities.User", "User")
                        .WithMany("UserSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_sessions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.Client", b =>
                {
                    b.Navigation("ClientProjects");
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.Item", b =>
                {
                    b.Navigation("ItemExpenses");

                    b.Navigation("ItemImages");

                    b.Navigation("ItemSpecifications");
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.ItemType", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("ProjectItems");
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.Project", b =>
                {
                    b.Navigation("ProjectItems");

                    b.Navigation("ProjectRequestProofs");

                    b.Navigation("Quotation")
                        .IsRequired();
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.ProjectItem", b =>
                {
                    b.Navigation("ProjectItemExpenses");

                    b.Navigation("ProjectItemImages");

                    b.Navigation("ProjectItemSpecifications");
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.Quotation", b =>
                {
                    b.Navigation("QuotationAdditionals");

                    b.Navigation("QuotationComputationConstants");
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ANLairQuotationSystem.Entities.User", b =>
                {
                    b.Navigation("CreatedClients");

                    b.Navigation("CreatedProjectRequestProofs");

                    b.Navigation("CreatedProjects");

                    b.Navigation("UserSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
